x-kafka-common: &kafka-common
  image: apache/kafka:4.2.0
  environment: &kafka-common-env
    KAFKA_PROCESS_ROLES: broker,controller
    KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    KAFKA_MIN_INSYNC_REPLICAS: 2
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    CLUSTER_ID: "Z2cnSEZUT7CODxXhE4GQew"
services:
  postgres:
    image: postgres:18.3
    container_name: candidate-service-postgres
    environment:
      POSTGRES_DB: candidate_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - candidate-service-pg-data:/var/lib/postgresql
  kafka-1:
    <<: *kafka-common
    container_name: kafka-1
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:29094
    ports:
      - "29092:9092"
      - "29094:9094"
    volumes:
      - kafka-1-data:/var/lib/kafka/data
  kafka-2:
    <<: *kafka-common
    container_name: kafka-2
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:39094
    ports:
      - "39092:9092"
      - "39094:9094"
    volumes:
      - kafka-2-data:/var/lib/kafka/data
  kafka-3:
    <<: *kafka-common
    container_name: kafka-3
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,EXTERNAL://localhost:49094
    ports:
      - "49092:9092"
      - "49094:9094"
    volumes:
      - kafka-3-data:/var/lib/kafka/data
  redis:
    image: redis:8.6.1
    container_name: calculation-service-redis
    ports:
      - "6379:6379"
    volumes:
      - calculation-service-redis-data:/data
  mongo:
    image: mongo:8.2.6
    container_name: offer-service-mongo
    ports:
      - "27017:27017"
    volumes:
      - offer-service-mongo-data:/data/db
volumes:
  candidate-service-pg-data:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
  calculation-service-redis-data:
  offer-service-mongo-data: