spring.application.name=candidate-service

spring.datasource.url=jdbc:postgresql://localhost:5432/candidate_service
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml