spring.application.name=candidate-service

spring.datasource.url=jdbc:postgresql://localhost:5432/candidate_service
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.kafka.producer.acks=all
spring.kafka.producer.retries=2147483647
spring.kafka.producer.properties.init.connections.on.startup=true
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.bootstrap-servers=localhost:29094,localhost:39094,localhost:49094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

kafka.topics.candidate-created.name=candidate-created
kafka.topics.candidate-created.partitions=1
kafka.topics.candidate-created.replicas=3
kafka.topics.candidate-created.retention-ms=1209600000
kafka.topics.candidate-created.retention-bytes=1073741824