spring.application.name=calculation-service

server.port=8081

spring.kafka.producer.properties.init.connections.on.startup=true
spring.kafka.bootstrap-servers=localhost:29094,localhost:39094,localhost:49094
spring.kafka.consumer.group-id=calculation-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# TODO - decouple schema between services with Avro Registry
spring.kafka.consumer.properties.spring.json.type.mapping=candidateCreated:com.github.losevskiyfz.calculationservice.event.CandidateCreatedEvent

spring.kafka.producer.acks=all
spring.kafka.producer.retries=2147483647
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

kafka.topics.candidate-created.name=candidate-created

kafka.topics.calculation-completed.name=calculation-completed
kafka.topics.calculation-completed.partitions=1
kafka.topics.calculation-completed.replicas=3
kafka.topics.calculation-completed.retention-ms=1209600000
kafka.topics.calculation-completed.retention-bytes=1073741824

spring.data.redis.host=localhost
spring.data.redis.port=6379
redis.cache.ttl=14d