spring.application.name=offer-service

server.port=8082

spring.kafka.bootstrap-servers=localhost:29094,localhost:39094,localhost:49094
spring.kafka.consumer.group-id=offer-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=calculationCompleted:com.github.losevskiyfz.offerservice.event.CalculationCompletedEvent

kafka.listener.topics.calculation-completed.name=calculation-completed

spring.data.mongodb.uri=mongodb://localhost:27017/offer_service
management.endpoints.web.exposure.include=env,health